## 1. Import Necessary Libraries

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, roc_auc_score,accuracy_score,confusion_matrix
import matplotlib.pyplot as plt

## 2. Import Dataset

In [2]:
claimants_data=pd.read_csv("claimants.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

## 3. Data Understanding

In [3]:
claimants_data.shape

(1340, 7)

In [4]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

## 4. Data Preparation

### 4.1 Data Cleaning

In [6]:
claimants_data.dropna(inplace=True)
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [7]:
1340-1096

244

In [8]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

### 4.2 Seprate inputs and outputs

In [9]:
x=claimants_data.drop(labels=["CASENUM","ATTORNEY"],axis=1)
x

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [10]:
y=claimants_data["ATTORNEY"]
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

## 5. Model Building

In [11]:
Logistic_model=LogisticRegression()

## 6. Model Training

In [12]:
Logistic_model.fit(x,y)

LogisticRegression()

## 7. Model Testing

### Training Data

In [13]:
y_pred=Logistic_model.predict(x)
y_pred

array([0, 1, 1, ..., 1, 0, 1], shape=(1096,))

In [14]:
claimants_data["Predicted_output"]=Logistic_model.predict(x)
claimants_data

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS,Predicted_output
0,5,0,0.0,1.0,0.0,50.0,34.940,0
1,3,1,1.0,0.0,0.0,18.0,0.891,1
2,66,1,0.0,1.0,0.0,5.0,0.330,1
3,70,0,0.0,1.0,1.0,31.0,0.037,0
4,96,1,0.0,1.0,0.0,30.0,0.038,1
...,...,...,...,...,...,...,...,...
1334,34104,1,1.0,1.0,0.0,16.0,0.060,1
1336,34110,0,1.0,1.0,0.0,46.0,3.705,0
1337,34113,1,1.0,1.0,0.0,39.0,0.099,1
1338,34145,0,1.0,0.0,0.0,8.0,3.177,0
1339,34153,1,1.0,1.0,0.0,30.0,0.688,1

## 8. Model Evaluation

In [15]:
from sklearn.metrics import accuracy_score

### Training Accuracy

In [16]:
accuracy_score(y,y_pred)

0.708029197080292

## 9. Model Deployment

In [17]:
from pickle import dump

In [18]:
dump(Logistic_model,open("claimant.pkl","wb"))

# THE END

In [19]:
confusion_matrix(y,y_pred)

array([[381, 197],
       [123, 395]])